packages:
  - 'apps/cli'
  - 'apps/server'
  - 'apps/web'
  - 'packages/auth'
  - 'packages/batch-engine'
  - 'packages/cad-import'
  - 'packages/config'
  - 'packages/contracts'
  - 'packages/core'
  - 'packages/database'
  - 'packages/diagnostics'
  - 'packages/drawing-model'
  - 'packages/dwg-adapter'
  - 'packages/dxf-adapter'
  - 'packages/file-ingest'
  - 'packages/plot-engine'
  - 'packages/presets'
  - 'packages/renderer-pdf'
  - 'packages/renderer-svg'
  - 'packages/renderer-webgl'
  - 'packages/storage'
  - 'packages/cad-simple-viewer'
  - 'packages/three-renderer'
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
overrides:
  '@mlightcad/data-model': '^1.12.1'
  '@mlightcad/libredwg-converter': '^3.12.1'
  '@mlightcad/mtext-input-box': '^0.2.22'
  '@mlightcad/mtext-renderer': '^0.12.1'
  element-plus: '^2.12.0'
  glob: '^13.0.6'
  lodash-es: '4.17.21'
  three: '^0.172.0'
  vue: '^3.4.21'
